"""Import-time OpenMP preprocessing and compilation support.

This module integrates the `omp4py` preprocessing pipeline into Python's
import machinery, allowing registered packages to be automatically
transformed and optionally compiled during module import.

Packages registered through `set_omp_package` are intercepted by a custom
meta pathfinder and loaded using specialized loaders that apply the
OpenMP transformation pipeline transparently before execution.

Two execution modes are supported:

- Pure Python preprocessing (`Omp4pyLoader`)
- Native extension compilation using Cython (`Omp4pyCythonLoader`)

The import system maintains a dedicated `__omp__` cache directory used to
store transformed sources, generated bytecode, and compiled extensions.
This separation prevents conflicts with the standard Python import cache
while allowing transformed modules to be reused across executions.

The module also tracks whether preprocessing regenerated transformed
sources, allowing compiled extensions to be rebuilt only when necessary.
"""

import sys
import types
from collections.abc import Sequence
from importlib.machinery import ExtensionFileLoader, ModuleSpec, PathFinder, SourceFileLoader
from pathlib import Path
from threading import Lock

from omp4py.core.options import Options

__all__ = ["OMP_FOLDER", "set_omp_package"]

OMP_FOLDER: str = "__omp__"
_init_lock: Lock = Lock()
omp_packages: dict[str, Options] = {}


class Omp4pyFinder:
    """Meta path finder for OpenMP-aware package imports.

    This finder integrates the `omp4py` preprocessing system into
    Python's import mechanism by intercepting imports belonging to
    registered packages.

    When a matching package is detected, the default source loader is
    replaced with either `Omp4pyLoader` or `Omp4pyCythonLoader`,
    depending on whether native compilation is enabled.

    The finder only affects explicitly registered packages and leaves
    all unrelated imports unchanged.
    """

    @staticmethod
    def find_spec(
        name: str,
        import_path: Sequence[str] | None = None,
        target_module: types.ModuleType | None = None,
    ) -> ModuleSpec | None:
        """Locate and customize the import specification for registered packages.

        This method participates in Python's `sys.meta_path` import protocol.
        When the requested module belongs to a package registered through
        `set_omp_package`, the default loader is replaced with an omp4py-aware
        loader capable of preprocessing or compiling the module before
        execution.

        Depending on the package configuration:

        - `Omp4pyLoader` is used for transformed pure-Python execution.
        - `Omp4pyCythonLoader` is used for native extension compilation.

        Modules outside registered packages are ignored and resolved by the
        normal Python import system.

        Args:
            name (str):
                Fully qualified module name being imported.

            import_path (Sequence[str] | None):
                Search path used during module resolution.

            target_module (types.ModuleType | None):
                Existing module instance used during reload operations.

        Returns:
            ModuleSpec | None:
                Modified module specification using an omp4py-aware loader,
                or `None` if the module is not managed by `omp4py`.
        """
        if (opt := omp_packages.get(name.rsplit(".", maxsplit=1)[0])) is None:
            return None

        spec: ModuleSpec | None = PathFinder.find_spec(name, import_path, target_module)
        if spec is not None and isinstance(spec.loader, SourceFileLoader) and spec.origin is not None:
            if opt.compile:
                spec.loader = Omp4pyCythonLoader(name, spec.origin)
            else:
                spec.loader = Omp4pyLoader(name, spec.origin)
        return spec


class Omp4pyLoader(SourceFileLoader):
    """Source loader that preprocesses modules using `omp4py`.

    This loader extends the standard Python source loader to apply
    OpenMP transformations before module compilation.

    Source files are transformed into an intermediate representation
    stored inside the `__omp__` cache directory. The resulting code is
    then compiled normally through Python's import system.

    The loader also redirects bytecode cache operations to the dedicated
    OpenMP cache directory, ensuring separation from the standard
    `__pycache__` hierarchy.

    Attributes:
        need_recompile (bool):
            Indicates whether the transformed module source was
            regenerated during the current import operation. This flag
            is used by `Omp4pyCythonLoader` to determine whether an
            existing compiled extension must be rebuilt.
    """

    need_recompile: bool

    def __init__(self, *args, **kwargs) -> None:  # noqa: ANN002, ANN003
        self.need_recompile = False
        super().__init__(*args, **kwargs)

    def create_module(self, spec: ModuleSpec) -> types.ModuleType | None:
        """Create a module using the transformed OpenMP cache path.

        The module specification origin is redirected to the corresponding
        location inside the `__omp__` cache directory before normal module
        creation continues.

        This ensures that generated bytecode and related cache files are
        associated with the transformed source rather than the original
        Python module.

        Args:
            spec (ModuleSpec):
                Import specification associated with the module.

        Returns:
            types.ModuleType | None:
                Newly created module instance or `None` if default module
                creation should be used.
        """
        spec.origin = str(Path(self.path).parent / OMP_FOLDER / Path(self.path).name)
        return super().create_module(spec)

    def source_to_code(self, data, path, *args, **kwargs) -> types.CodeType:  # noqa: ANN001, ANN002, ANN003
        """Transform module source code using the OpenMP preprocessor.

        The raw source code is parsed into an AST, passed through the
        `omp4py` transformation pipeline, and compiled into executable
        bytecode.

        The transformed source is stored inside the `__omp__` cache
        directory and marked as requiring recompilation for compiled
        extension workflows.

        Args:
            data:
                Raw source code of the module.

            path:
                Filesystem path of the source module.

            *args:
                Additional positional arguments forwarded to the parent
                implementation.

            **kwargs:
                Additional keyword arguments forwarded to the parent
                implementation.

        Returns:
            types.CodeType:
                Compiled code object generated from the transformed source.
        """
        self.need_recompile = True
        if isinstance(path, bytes):
            path = path.decode()
        if isinstance(data, bytes):
            data = data.decode()

        omp_path: str = str(Path(path).parent / OMP_FOLDER / Path(path).name)
        if isinstance(data, str):
            from omp4py.core import preprocessor  # noqa: PLC0415  Lazy import, only when needed (no cache available)

            opt: Options = omp_packages[self.name.rsplit(".", maxsplit=1)[0]]
            data = preprocessor.process_source(data, omp_path, opt)
            path = omp_path
        return super().source_to_code(data, path, *args, **kwargs)

    def get_data(self, path: str) -> bytes:
        """Load source or cache data for a transformed module.

        Requests targeting `__pycache__` entries are transparently
        redirected to the corresponding location inside the `__omp__`
        cache directory.

        This allows Python's import system to reuse bytecode generated from
        transformed modules without interfering with the standard cache
        associated with the original source files.

        Args:
            path (str):
                Requested filesystem path.

        Returns:
            bytes:
                Raw file contents loaded from disk.

        Raises:
            OSError:
                If cache access is disabled through preprocessing options.
        """
        target = Path(path)
        if target.parent.name == "__pycache__":
            if omp_packages[self.name.rsplit(".", maxsplit=1)[0]].ignore_cache:
                msg = "Cache directory is detected and ignored"
                raise OSError(msg)
            target = Path(*target.parts[:-2], OMP_FOLDER, *target.parts[-2:])

        return super().get_data(str(target))

    def set_data(self, path: str, *args, **kwargs) -> None:  # noqa: ANN002, ANN003
        """Store generated cache data inside the OpenMP cache directory.

        Cache writes targeting `__pycache__` are redirected to the matching
        location inside the `__omp__` directory, ensuring that transformed
        modules maintain an isolated cache hierarchy.

        Args:
            path (str):
                Destination cache path requested by the import system.

            *args:
                Additional positional arguments forwarded to the parent
                implementation.

            **kwargs:
                Additional keyword arguments forwarded to the parent
                implementation.
        """
        target = Path(path)
        if Path(path).parent.name == "__pycache__":
            target = Path(*target.parts[:-2], OMP_FOLDER, *target.parts[-2:])
        super().set_data(str(target), *args, **kwargs)


class Omp4pyCythonLoader(ExtensionFileLoader):
    """Extension loader for compiled OpenMP modules.

    This loader extends the import pipeline to support automatic
    compilation of transformed modules into native extension binaries
    using Cython.

    Before loading the extension, the loader ensures that the
    transformed source cache is up to date. Existing compiled modules
    are reused whenever possible, while outdated or missing binaries
    are rebuilt automatically.
    """

    def create_module(self, spec: ModuleSpec) -> types.ModuleType:
        """Create or load a compiled OpenMP extension module.

        The loader first preprocesses the source module using
        `Omp4pyLoader` to determine whether the transformed source has
        changed.

        If a valid compiled extension already exists and the transformed
        source did not require regeneration, the existing binary is reused.
        Otherwise, the module is recompiled using the Cython build system.

        Args:
            spec (ModuleSpec):
                Import specification associated with the extension module.

        Returns:
            types.ModuleType:
                Loaded extension module instance.
        """
        omp_path = str(Path(self.path).parent / OMP_FOLDER / Path(self.path).name)

        cache = Omp4pyLoader(self.name, self.path)
        cache.get_code(self.name)
        need_cythonize = cache.need_recompile

        if not need_cythonize:
            ext_spec: ModuleSpec | None = PathFinder.find_spec(self.name, [str(Path(omp_path).parent)])
            if ext_spec and isinstance(ext_spec.loader, ExtensionFileLoader):
                spec.origin = ext_spec.origin
            else:
                need_cythonize = True

        if need_cythonize:
            from omp4py.core.preprocessor.cbuild import cythonize  # noqa: PLC0415  Lazy import, only when needed

            opt: Options = omp_packages[self.name.rsplit(".", maxsplit=1)[0]]
            spec.origin = self.path = cythonize(self.name, str(Path(omp_path).parent), omp_path, opt, inplace=False)
        spec.cached = None

        return super().create_module(spec)


def set_omp_package(pkg: str, opt: Options) -> None:
    """Register a package for import-time OpenMP preprocessing.

    Registered packages are automatically processed by the `omp4py`
    import hook whenever their modules are imported.

    Depending on the provided options, modules may either be transformed
    into pure Python code or compiled into native extensions using
    Cython.

    On first use, the global `Omp4pyFinder` is installed into
    `sys.meta_path` to activate the import integration layer.

    Args:
        pkg (str):
            Package name to register for preprocessing.

        opt (Options):
            Preprocessing and compilation configuration associated with
            the package.
    """
    if len(omp_packages) == 0:
        with _init_lock:
            if len(omp_packages) == 0:
                sys.meta_path.insert(0, Omp4pyFinder())
    omp_packages[pkg] = opt
