"""Source access and diagnostics for OpenMP directive parsing.

This module provides utilities to map parser and AST diagnostics back to the
original Python source code containing an ``omp()`` directive.

It defines ``SourceView``, which swns the source text and provides helpers to:

* Translate directive-relative spans to file-global spans
* Extract source fragments
* Build annotated ``SyntaxError`` instances

Two coordinate systems are used throughout:
- Relative spans (relative to the directive, 1-based lines)
- Global spans (relative to the full source file)

``SourceView`` bridges these systems using the directive's global span as an
anchor. Line numbers are 1-based and column offsets are 0-based, matching
Python’s ``SyntaxError`` conventions.

This module does not perform parsing; it only formats and contextualizes
errors produced by the parser.
"""
from __future__ import annotations

import typing
from dataclasses import dataclass

from .tree import Span
from pathlib import Path

if typing.TYPE_CHECKING:
    from .openmp_parser import Token, Meta, UnexpectedToken

__all__ = ["SourceView"]

_TOKEN_DISPLAY: dict[str, str] = {
    # Reduction operators
    "PLUS"        : '"+"',
    "MINUS"       : '"-"',
    "MULT"        : '"*"',
    "BITWISE_AND" : '"&"',
    "BITWISE_OR"  : '"|"',
    "BITWISE_XOR" : '"^"',
    "LOGIC_AND"   : '"and"',
    "LOGIC_OR"    : '"or"',
    "MAX"         : '"max"',
    "MIN"         : '"min"',

    #### OPTIONS ####
    # TODO: add quotes here?
    # Schedule
    "STATIC"  : "static",
    "DYNAMIC" : "dynamic",
    "GUIDED"  : "guided",
    "AUTO"    : "auto",
    "RUNTIME" : "runtime",

    # Default
    "NONE"   : "none",
    "SHARED" : "shared",

    # Atomic
    "READ"    : "read",
    "WRITE"   : "write",
    "UPDATE"  : "update",
    "CAPTURE" : "capture",

    #### OTHER ####
    "INTEGER"    : "integer",
    "IDENTIFIER" : "variable name",

    #### DEFINED BY LARK ####
    "LPAR"  : '"("',
    "RPAR"  : '")"',
    "COMMA" : '","',
    "COLON" : '":"',
    "$END"  : "end of input",
}


class SourceView:
    """View and query helper for directive source code.

    This class encapsulates access to the original source code associated with
    an ``omp()`` directive invocation. It stores the full file contents and
    provides utilities to:

    - Extract text fragments using line/column spans
    - Convert *relative* spans (inside the directive) to *global* file spans
    - Compute absolute positions for diagnostics
    - Construct rich ``SyntaxError`` objects with annotations and notes

    ### Spans and coordinate systems

    Two coordinate systems are used throughout:

    1. **Relative spans**
       - Generated by ``AstTransformer``
       - Relative to the start of the directive text
       - Line numbers are 1-based

    2. **Global spans**
       - Refer to the full source file
       - Used for error reporting, annotations, and text extraction

    The ``span`` attribute of this class represents the *global* span of the
    directive within the source file and is used as the anchor to translate
    relative spans into global ones.

    All line numbers are 1-based, and column offsets are 0-based, matching
    Python's ``SyntaxError`` conventions.
    """
    def __init__(
        self,
        span: Span,
        filename: str,
        lines: list[str],
        directive: str
    ) -> None:
        self.span = span
        self.filename = filename
        self.lines = lines
        self.directive = directive

    @staticmethod
    def from_file(span: Span, filename: str, directive: str) -> SourceView:
        """Construct a SourceView by loading source lines from a file.

        Args:
            span (tree.Span): Global span locating the directive in the file.
            filename (str): Path to the source file.
            directive (str): Raw text of the directive.
        Returns:
            SourceView: A new instance populated with the file contents.
        """
        return SourceView(
            span,
            filename,
            Path(filename).read_text().splitlines(),
            directive,
        )

    #### TEXT RETRIEVAL ########################################################

    def source_line(self, lineno: int) -> str:
        """Return a single line of source code.

        Args:
            lineno (int): 1-based line number.
        Returns:
            str: The corresponding line of source code.
        """
        if not self.lines:
            return ''
        return self.lines[lineno - 1]

    def source_text(self, span: Span) -> str:
        """Extract source text referenced by a *global* span.

        Args:
            span (tree.Span): Global span identifying a region of the source file.
        Returns:
            str: The concatenated source text covered by the span.
        """
        if span.lineno == span.end_lineno:
            return self.lines[span.lineno - 1][span.offset:span.end_offset]

        parts = [self.lines[span.lineno - 1][span.offset:]]
        parts.extend(self.lines[span.lineno:span.end_lineno - 1])
        parts.append(self.lines[span.end_lineno - 1][:span.end_offset])

        return "".join(parts)

    def directive_text(self, span: Span) -> str:
        """Extract source text referenced by a *relative* span.

        The span is first translated to global coordinates using
        :meth:`global_span`.

        Args:
            span (tree.Span): Span relative to the directive text.
        Returns:
            str: The corresponding text in the source file.
        """
        span = self.global_span(span)
        return self.source_text(span)

    #### SPAN TRANSFORMATION ###################################################

    def global_span(self, span: Span) -> Span:
        """Convert a span relative to the directive start into a global(file-level) span."""
        line_offset      = max(self.span.lineno, 1)
        start_col_offset = self.span.offset if span.lineno == 1 else 0
        end_col_offset   = self.span.offset if span.end_lineno == 1 else 0

        return Span(
            line_offset + span.lineno - 1,
            start_col_offset + span.offset,
            line_offset + span.end_lineno - 1,
            end_col_offset + span.end_offset,
        )

    def absolute_position(
        self,
        anchor: Span,
        rel_line: int,
        rel_col: int,
        first_offset: int = 0,
    ) -> tuple[int, int]:
        """Convert a position relative to an anchor span into absolute coordinates.

        No validation is performed.

        Args:
            anchor (tree.Span): Global anchor span.
            rel_line (int): Line number relative to the anchor (1-based).
            rel_col (int): Column number relative to the anchor (1-based).
            first_offset (int): Additional column offset applied only if ``rel_line == 1``.
        Returns:
            tuple[int, int]: Absolute (line, column) position in the source file.
        """
        abs_line = anchor.lineno + rel_line - 1
        abs_col = (
            anchor.offset + first_offset + rel_col - 1 # offset only applies on the first line
            if rel_line == 1
            else rel_col - 1
        )
        return abs_line, abs_col


    #### ERRORS ################################################################

    def syntax_error(
        self,
        message,
        span: Span,
        *,
        diagnostics: list[tuple[str, Span]] | None = None,
    ) -> SyntaxError:
        """Construct a ``SyntaxError`` with optional diagnostic notes.

        Args:
            message (str): Error message.
            span (tree.Span): Relative span identifying the error location.
            diagnostics: Optional list of (message, span) pairs used to generate additional annotated notes.
        Returns:
            SyntaxError: A fully populated ``SyntaxError`` instance.
        """
        span = self.global_span(span)
        text = self.source_line(span.lineno)

        error: SyntaxError
        if span.end_lineno < 0 or span.end_offset < 0:
            error = SyntaxError(
                message,
                (self.filename, span.lineno, span.offset + 1, text),
            )
        else:
            error = SyntaxError(
                message,
                (self.filename, span.lineno, span.offset + 1, text, span.end_lineno, span.end_offset + 1),
            )

        if diagnostics is not None:
            for msg, span in diagnostics:
                span = self.global_span(span)
                line, cursor = self.annotate(span, indent=2, show_lineno=True)
                error.add_note(f"  note: {msg}\n{line}{cursor[:-1]}")

        return error


    def error(
        self,
        error: UnexpectedToken,
        diagnostics: list[tuple[str, Span]] | None = None,
    ) -> SyntaxError:
        """Convert a parser ``UnexpectedToken`` into a ``SyntaxError``.

        Args:
            error (lark.exceptions.UnexpectedToken): Parser error raised by Lark.
            diagnostics: Optional diagnostic notes forwarded to :meth:`syntax_error`.
        Returns:
            SyntaxError: A formatted syntax error suitable for user display.
        """
        msg, use_one_char_span = self._msg_from_error(error)

        token = typing.cast("Token", error.token)
        span = Span(
            token.line or 1,
            (token.column or 1) - 1,
            token.end_line       if token.end_line   is not None else -1,
            token.end_column - 1 if token.end_column is not None else -1,
        )
        if use_one_char_span:
            span.end_lineno = -1
            span.end_offset = -1

        return self.syntax_error(msg, span, diagnostics=diagnostics)


    def _msg_from_error(self, error: UnexpectedToken) -> tuple[str, bool]:
        token = typing.cast("Token", error.token)

        #### Expected tokens ####

        expected_token_names: list[str] = []
        expected_clause = False
        expected_expr   = False

        for expected_token in sorted(error.expected):
            if expected_token.endswith("_DIRECTIVE"):
                # Directive must be at top level,
                # if that was not provided, everything else is wrong.
                return "expected OpenMP directive.", False

            if expected_token.endswith("_CLAUSE"):
                expected_clause = True
                continue

            if expected_token == "PY_ATOM":
                expected_expr = True
                continue

            expected_token_names.append(_TOKEN_DISPLAY.get(expected_token, f'"{expected_token}"'))

        # Make sure OpenMP clause is last
        if expected_clause:
            expected_token_names.append("OpenMP clause")

        # Convert to expected_str
        expected_str = (
            expected_token_names[0]
            if len(expected_token_names) == 1
            else ", ".join(expected_token_names[:-1]) + f" or {expected_token_names[-1]}"
        )

        #### Actual token received ####

        # If the token is PY_ATOM, it means that we got unexpected characters.
        # The problem here is that PY_ATOM will consume everything until a parentheses,
        # therefore the error location will be wrong.
        if token.type == "PY_ATOM":
            first_char = token[0]
            display = "integer" if first_char.isdigit() else f"'{first_char}'"
            return f'expected {expected_str} instead of {display}.', True

        if token.type.endswith(("_DIRECTIVE", "_CLAUSE")):
            return f'"{token}" is not valid for this directive.', False

        found_token = _TOKEN_DISPLAY.get(token.type, f'"{token}"')
        if expected_expr:
            # Unbalanced parentheses
            if token.type == "$END":
                return f'expected ")" before {found_token}.', False
            return f"expected Python expression before {found_token}.", False

        return f"expected {expected_str} before {found_token}.", False


    def annotate(self, span: Span, indent: int=0, show_lineno: bool=False) -> tuple[str, str]:
        """Generate an annotated source line and cursor indicator.

        The given Span must be global.

        Args:
            span (tree.Span): Global span to highlight.
            indent (int): Number of spaces to indent both line and cursor.
            show_lineno (bool): Whether to prefix the line with its line number.
        Returns:
            tuple[str, str]: (source line, cursor line)
        """

        line = self.lines[span.lineno - 1] + "\n"
        width = (
            span.end_offset - span.offset
            if span.lineno == span.end_lineno
            else len(line) - span.offset
        )
        cursor = " " * span.offset + "^" * width + "\n"

        if show_lineno:
            line = f"{span.lineno:>5} | {line}"
            cursor = " "*5 + " | " + cursor

        line   = " " * indent + line
        cursor = " " * indent + cursor

        return line, cursor


