"""Global runtime functions exported for generated OpenMP code.

This package defines and exposes the complete set of runtime functions
used by code generated by `omp4py`.

The purpose of this module is not to implement high-level logic, but to
act as a stable and explicit interface between the OpenMP code generator
and the underlying runtime system. All functions listed here correspond
to runtime entry points that may be emitted directly by the preprocessor
during transformation of OpenMP constructs.

This includes operations related to parallel regions, task management,
synchronization, scheduling, and other OpenMP runtime services.

By explicitly listing and exposing these functions, the runtime ensures
that generated code can rely on a consistent API surface, regardless of
internal implementation changes.
"""

from omp4py.runtime.tasks import barrier, parallel, threadprivate, threadprivates  # noqa: F401
